# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f9712b8100622316488e4ad88675f212d9d37b77ac65201cc0569bd7a95c50571c4c9555471e9458efd496c134a39ad2183d3d526ecfb556df575cb45f2300

test:
  secret_key_base: 3a4f91e0107fe0fceeb468bf719d54090334cbb4eda8842b0c4bfd14a181b4fa398f467a39b474670ee848a93198d7c314ef3bdde4ad7ed4cb4889132c003d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
